### ISSUE TITLE
CSS两端对齐

### ISSUE THREAD

**Issue by hm496** [hm496/blog#3]
```css
    .demo {
      text-align:justify;
      text-align-last:justify; /*Safari不支持*/
    }

    /*兼容Safari*/
    .demo::after {
      content:"";
      display:inline-block;
      height:0;
      line-height:0;
      clear:both;
      width:100%;
    }
```
